/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentIdRouteImport } from './routes/student.$id'
import { Route as ParentRevealRouteImport } from './routes/parent.reveal'
import { Route as LeaderboardClassIdRouteImport } from './routes/leaderboard.$classId'
import { Route as KnightStudentIdRouteImport } from './routes/knight.$studentId'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStandardsRouteImport } from './routes/admin.standards'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as TeacherEvaluateClassIdRouteImport } from './routes/teacher.evaluate.$classId'
import { Route as TeacherClassIdRouteImport } from './routes/teacher.class.$id'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIdRoute = StudentIdRouteImport.update({
  id: '/student/$id',
  path: '/student/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRevealRoute = ParentRevealRouteImport.update({
  id: '/parent/reveal',
  path: '/parent/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardClassIdRoute = LeaderboardClassIdRouteImport.update({
  id: '/leaderboard/$classId',
  path: '/leaderboard/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnightStudentIdRoute = KnightStudentIdRouteImport.update({
  id: '/knight/$studentId',
  path: '/knight/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStandardsRoute = AdminStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherEvaluateClassIdRoute = TeacherEvaluateClassIdRouteImport.update({
  id: '/evaluate/$classId',
  path: '/evaluate/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassIdRoute = TeacherClassIdRouteImport.update({
  id: '/class/$id',
  path: '/class/$id',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/knight/$studentId': typeof KnightStudentIdRoute
  '/leaderboard/$classId': typeof LeaderboardClassIdRoute
  '/parent/reveal': typeof ParentRevealRoute
  '/student/$id': typeof StudentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/class/$id': typeof TeacherClassIdRoute
  '/teacher/evaluate/$classId': typeof TeacherEvaluateClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/knight/$studentId': typeof KnightStudentIdRoute
  '/leaderboard/$classId': typeof LeaderboardClassIdRoute
  '/parent/reveal': typeof ParentRevealRoute
  '/student/$id': typeof StudentIdRoute
  '/admin': typeof AdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/class/$id': typeof TeacherClassIdRoute
  '/teacher/evaluate/$classId': typeof TeacherEvaluateClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/knight/$studentId': typeof KnightStudentIdRoute
  '/leaderboard/$classId': typeof LeaderboardClassIdRoute
  '/parent/reveal': typeof ParentRevealRoute
  '/student/$id': typeof StudentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/class/$id': typeof TeacherClassIdRoute
  '/teacher/evaluate/$classId': typeof TeacherEvaluateClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/classes'
    | '/admin/import'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/standards'
    | '/admin/students'
    | '/admin/teachers'
    | '/knight/$studentId'
    | '/leaderboard/$classId'
    | '/parent/reveal'
    | '/student/$id'
    | '/admin/'
    | '/teacher/'
    | '/teacher/class/$id'
    | '/teacher/evaluate/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin/calendar'
    | '/admin/classes'
    | '/admin/import'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/standards'
    | '/admin/students'
    | '/admin/teachers'
    | '/knight/$studentId'
    | '/leaderboard/$classId'
    | '/parent/reveal'
    | '/student/$id'
    | '/admin'
    | '/teacher'
    | '/teacher/class/$id'
    | '/teacher/evaluate/$classId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/classes'
    | '/admin/import'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/standards'
    | '/admin/students'
    | '/admin/teachers'
    | '/knight/$studentId'
    | '/leaderboard/$classId'
    | '/parent/reveal'
    | '/student/$id'
    | '/admin/'
    | '/teacher/'
    | '/teacher/class/$id'
    | '/teacher/evaluate/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  KnightStudentIdRoute: typeof KnightStudentIdRoute
  LeaderboardClassIdRoute: typeof LeaderboardClassIdRoute
  ParentRevealRoute: typeof ParentRevealRoute
  StudentIdRoute: typeof StudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/$id': {
      id: '/student/$id'
      path: '/student/$id'
      fullPath: '/student/$id'
      preLoaderRoute: typeof StudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/reveal': {
      id: '/parent/reveal'
      path: '/parent/reveal'
      fullPath: '/parent/reveal'
      preLoaderRoute: typeof ParentRevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$classId': {
      id: '/leaderboard/$classId'
      path: '/leaderboard/$classId'
      fullPath: '/leaderboard/$classId'
      preLoaderRoute: typeof LeaderboardClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knight/$studentId': {
      id: '/knight/$studentId'
      path: '/knight/$studentId'
      fullPath: '/knight/$studentId'
      preLoaderRoute: typeof KnightStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/standards': {
      id: '/admin/standards'
      path: '/standards'
      fullPath: '/admin/standards'
      preLoaderRoute: typeof AdminStandardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/evaluate/$classId': {
      id: '/teacher/evaluate/$classId'
      path: '/evaluate/$classId'
      fullPath: '/teacher/evaluate/$classId'
      preLoaderRoute: typeof TeacherEvaluateClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/class/$id': {
      id: '/teacher/class/$id'
      path: '/class/$id'
      fullPath: '/teacher/class/$id'
      preLoaderRoute: typeof TeacherClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStandardsRoute: typeof AdminStandardsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminImportRoute: AdminImportRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStandardsRoute: AdminStandardsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeacherRouteChildren {
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassIdRoute: typeof TeacherClassIdRoute
  TeacherEvaluateClassIdRoute: typeof TeacherEvaluateClassIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassIdRoute: TeacherClassIdRoute,
  TeacherEvaluateClassIdRoute: TeacherEvaluateClassIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeacherRoute: TeacherRouteWithChildren,
  KnightStudentIdRoute: KnightStudentIdRoute,
  LeaderboardClassIdRoute: LeaderboardClassIdRoute,
  ParentRevealRoute: ParentRevealRoute,
  StudentIdRoute: StudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
